import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import localFont from 'next/font/local';

import './globals.css';
import { Header } from '@/views/Header';
import { Toaster } from 'react-hot-toast';

const open_sans = Open_Sans({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  variable: '--font-open-sans',
});

const dela_gothic = localFont({
  src: './DelaGothicOne-Regular.woff2',
  variable: '--font-dela-gothic',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${open_sans.variable} ${dela_gothic.variable} text-white`}
      >
        <Header />
        <main>{children}</main>
        <Toaster position="top-right" reverseOrder={true} />
      </body>
    </html>
  );
}
