import type { Metadata } from 'next';
import { Open_Sans, Dela_Gothic_One } from 'next/font/google';

import './globals.css';
import { Header } from '@/views/Header';

const open_sans = Open_Sans({
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  variable: '--font-open-sans',
});

const dela_gothic = Dela_Gothic_One({
  weight: '400',
  subsets: ['cyrillic', 'latin'],
  display: 'swap',
  variable: '--font-dela-gothic',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${open_sans.variable} ${dela_gothic.variable}`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
